from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
s=s.replace('      <p class="sub">예약, 환불, 작업 범위, A/S, 면책사항을 항목별로 확인하실 수 있습니다.</p>\n','')
s=s.replace('현장일지','현장기록')
s=s.replace('현장 기록을 지역, 서비스, 작업 범위 중심의 텍스트로 쌓아가는 공간입니다.','현장별 작업 내용과 정보성 콘텐츠를 지역, 서비스, 작업 범위 중심으로 정리하는 공간입니다.')
s=s.replace('실제 현장 기록을 지역, 서비스, 작업 범위 중심의 텍스트로 쌓아가는 공간입니다.','실제 현장 내용과 정보성 콘텐츠를 지역, 서비스, 작업 범위 중심으로 정리하는 공간입니다.')
s=s.replace('현장기록 구조 보기','현장기록 보기')
s=s.replace('인천 부평 입주청소 현장기록','인천 부평 입주청소 현장기록')
s=s.replace('송도 정리 청소 현장기록','송도 정리 청소 현장기록')
p.write_text(s,encoding='utf-8')
